[package]
name = "tapir-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.28.1"
eframe = "0.28.1"

catppuccin-egui = { version = "5.2", default-features = false, features = [
    "egui28",
] }
env_logger = "0.11.5"
egui_hooks = "0.5.0"
